# .github/workflows/rebuild.yml

# Name of the workflow as it appears in GitHub Actions
name: Scheduled Cloudflare Rebuild Trigger

# Triggers for this workflow
on:
  # Allows manual triggering via the GitHub Actions UI ("Run workflow" button)
  workflow_dispatch:

schedule:
    # Runs at 03:00 and 15:00 UTC every day
    - cron: '0 3,15 * * *'
    
jobs:
  # This job only exists to ping Cloudflare to start a build
  trigger:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Trigger Cloudflare Pages Build Hook
      - name: Trigger Cloudflare Pages Build
        run: |
          curl -X POST "${{ secrets.CLOUDFLARE_BUILD_HOOK }}"
